
stages:
  - build

6.1-apollolake:
  stage: build
  image: matthiaslohr/dsmpkg-env:6.1-apollolake
  before_script:
    - cd /tmp
    - echo `pwd`
  script:
    - git clone https://github.com/SynologyOpenSource/pkgscripts-ng.git /pkgscripts-ng
    - ./SynoBuildConf/build
    - ./SynoBuildConf/install

