
stages:
  - build

dsm6.2:
  stage: build
  before_script:
  script:
    - mkdir -p /synobuild/source
    - ln -sf ./ /synobuild/source/tmux
    - cd /synobuild/pkgscripts-ng
    - ./PkgCreate.py -v 6.2 tmux


