
6.1-apollolake:
  image: matthiaslohr/dsmpkg-env:6.1-apollolake
  script:
    - git clone https://github.com/SynologyOpenSource/pkgscripts-ng.git /pkgscripts-ng
    - ./SynoBuildConf/build
    - ./SynoBuildConf/install

